---
title: "Untitled"
output: html_document
---

```{r get the data}
## Get the data

library(jsonlite)
if(!file.exists("data")){dir.create("data")}

# business data
businessData<- stream_in(file("E:/RSpace/yelp_dataset/business.json"))
saveRDS(businessData,"./data/businessData.rds")
rm(businessData)

# checkin datastr(review)
checkinData<- stream_in(file("E:/RSpace/yelp_dataset/yelp_academic_dataset_checkin.json"))
saveRDS(checkinData,"./data/checkinData.rds")
rm(checkinData)

# review data
reviewData<- stream_in(file("E:/RSpace/yelp_dataset/yelp_academic_dataset_review.json"))
saveRDS(reviewData,"./data/reviewData.rds")
rm(reviewData)

# tip data
tipData<- stream_in(file("E:/RSpace/yelp_dataset/yelp_academic_dataset_tip.json"))
saveRDS(tipData,"./data/tipData.rds")
rm(tipData)

# user data
userData<- stream_in(file("E:/RSpace/yelp_dataset/yelp_academic_dataset_user.json"))
saveRDS(userData,"./data/userData.rds")
rm(userData)
```
```{r load review data,cache=TRUE}
review<- readRDS("C:/Users/michael.hunt/Rspace/JHU_CAP_data/reviewData.rds")
# review<- readRDS("E:/Rspace/JHU_CAP_data/reviewData.rds")
# review<- readRDS("C:/Users/Mike/Rspace/JHU_CAP_data/reviewData.rds")
```
```{r load business data}
business<-readRDS("C:/Users/michael.hunt/Rspace/JHU_CAP_data/businessData.rds")
# business<- readRDS("E:/Rspace/JHU_CAP_data/businessData.rds")
```

```{r load user data}
user<-readRDS("C:/Users/michael.hunt/Rspace/JHU_CAP_data/userData.rds")
# user<- readRDS("E:/Rspace/JHU_CAP_data/userData.rds")
```

```{r USA map,cache=TRUE}
library(raster)
library(sp)
# get USA state boundary data
adm <- readRDS("USA_adm1.rds")
# cornwall=adm[adm$NAME_2=="Cornwall",]
# rm(adm)
```
```{r USA map}
library(leaflet)
m<-leaflet() %>%
  addTiles() %>% # use default OpenStreetMap tile
  #addPolygons(data=adm, weight = 1,fillOpacity = 0.) %>%
  addMarkers (data=business,lng=business$longitude,lat=business$latitude) %>%
  setView(lng = -105, lat = 39, zoom = 3)# %>% # centre on USA
m
```

```{r geocode}
library(maps)
library(ggmap)
cities=c("Edinburgh","Karlsruhe","Pittsburgh","Charlotte","Urbana","Waterloo","Montreal","Madison","Las Vegas","Phoenix")
latlon<-geocode(cities,source="google",messaging=FALSE)
# points(latlon$lon, latlon$lat,pch=19, col="cyan4")

ma<-kmeans(cbind(business$longitude,business$latitude),latlon)
business$cluster=ma$cluster
uc<-cbind(cities,ma$centers,ma$size)
```

```{r edinburgh}
EdBus<-subset(business,business$cluster==1)
nrow(EdBus)
EdMap<-get_map(location="edinburgh",zoom=14)
ggmap(EdMap)
ggmap(EdMap) + geom_point(data = EdBus, aes(x = longitude, y = latitude,size=stars,colour=attributes$Alcohol,alpha=1-2*stars/10))
```

```{r edreviews}
library(lubridate)
library(dplyr)
EdRev= subset(review,review$business_id %in% EdBus$business_id)
rm(review)
EdBus<-subset(business,business$cluster==1)
nrow(EdBus)
EdMap<-get_map(location="edinburgh",zoom=14)
# ggmap(EdMap)
ggmap(EdMap) + geom_point(data = EdBus, aes(x = longitude, y = latitude,size=stars,colour=attributes$Alcohol,alpha=1-2*stars/10))
boxplot(data=EdRev,stars~month(date))
EFRev<-subset(EdRev,month(date)==8)
table(month(EdRev$date))
a<-sapply(split(EdRev$stars,month(EdRev$date)),mean)
plot(a)
plot(table((month(EdRev$date))))
```

```{r all of them}
HighRevCount<-data.frame(City=character(),
                         review_count=numeric(),
                         stringsAsFactors=FALSE)

for (i in 1:length(unique(business$cluster))){
  CityBus<-subset(business,business$cluster==i)
  HighRevCount$City[i]=uc[i]
  HighRevCount$review_count[i]=sum(CityBus$review_count>100)
  CityRev<-subset(review,review$business_id %in% CityBus$business_id)
  a<-sapply(split(CityRev$stars,month(CityRev$date)),mean)
  plot(a)
  title(main=uc[i])
  plot(table((month(CityRev$date))))
  title(main=uc[i])
  HighRevCount
}
```